language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE timesheet_db;'

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'